image: "python:3.9"

default:
  tags:
    - docker

stages:
  - test

variables:
  CODECOV_TOKEN: "c8bcf054-f0cb-4bf1-8866-1b862905ef89"

before_script:
  - make install

test: 
  stage: test
  script:
    - make test
    - bash <(curl -s https://codecov.io/bash)
  only:
    refs:
      - master
