language: python
os:
  - linux
  - osx
python:
  - 3.6
  - 3.7
  - 3.8
  - nightly

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("MyPkg")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
    - /^dev/

jobs:
  allow_failures:
  - julia: nightly
