language: python
os:
  - linux
python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - ls

install: make install

script:
  - make test

after_script:
  - coveralls

branches:
  only:
    - master
